version: '3.8'

services:
  humhub:
    image: mriedmann/humhub:stable
    ports:
      - "${HUMHUB_PORT}:80"
    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
      - "./uploads:/var/www/localhost/htdocs/uploads"
      - "./uploads/profile_image:/var/www/localhost/htdocs/uploads/profile_image" #Evita errores
      - "./modules:/var/www/localhost/htdocs/protected/modules"
      - "./logs/app.log:/var/www/localhost/htdocs/protected/runtime/logs/app.log" # Evita errores
    environment:
      HUMHUB_DB_USER: ${MYSQL_USER}
      HUMHUB_DB_PASSWORD: ${MYSQL_PASSWORD}
      HUMHUB_DB_HOST: ${MYSQL_HOST}
      HUMHUB_DB_NAME: ${MYSQL_DATABASE}
      HUMHUB_AUTO_INSTALL: ${HUMHUB_AUTO_INSTALL}
      HUMHUB_ADMIN_LOGIN: ${HUMHUB_ADMIN_LOGIN}
      HUMHUB_ADMIN_PASSWORD: ${HUMHUB_ADMIN_PASSWORD}
      HUMHUB_ADMIN_EMAIL: ${HUMHUB_ADMIN_EMAIL}
      WAIT_FOR_DB: ${WAIT_FOR_DB}
      HUMHUB_DEBUG: ${HUMHUB_DEBUG}
      HUMHUB_PROTO: ${HUMHUB_PROTO}
      HUMHUB_HOST: ${HUMHUB_HOST}
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: ${HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS}
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: ${HUMHUB_MAILER_SYSTEM_EMAIL_NAME}
      HUMHUB_MAILER_TRANSPORT_TYPE: ${HUMHUB_MAILER_TRANSPORT_TYPE}
      HUMHUB_MAILER_HOSTNAME: ${HUMHUB_MAILER_HOSTNAME}
      HUMHUB_MAILER_PORT: ${HUMHUB_MAILER_PORT}
      HUMHUB_MAILER_USERNAME: ${HUMHUB_MAILER_USERNAME}
      HUMHUB_MAILER_PASSWORD: ${HUMHUB_MAILER_PASSWORD}
      HUMHUB_MAILER_ENCRYPTION: ${HUMHUB_MAILER_ENCRYPTION}
      NGINX_KEEPALIVE_TIMEOUT: ${NGINX_KEEPALIVE_TIMEOUT}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_TIMEZONE: ${TZ}
      TZ: ${TZ}
    restart: unless-stopped
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 96M
  db:
    image: mariadb:10.2
    hostname: ${MYSQL_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 96M

volumes:
  config:
  uploads:
  modules:
